server:
  port: 9527

spring:
  application:
    name: microservice-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

info:
  app.name: gateway
  company.name: ziav
  build.artifactId: $project.artifactId$
  build.version: $project.version$

zuul:
  prefix: /sziit                                 # 路由前缀
  ignored-services: "*"                          # 忽略真实服务名，单个请填微服务名
  routes:                                        # 代理转发
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**